# -*- coding: utf-8 -*-
"""computerVision.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ATQFojzD2W-RD5RN1B3YWkbDBs6NpyLV
"""

!pip install matplotlib-venn

import numpy as np
import matplotlib.pyplot as plt

signal = np.array([1, 1, 1, 0,5, 1, 1, 0.5, 0.5, 0.5])

plt.stem(signal)
plt.show()

filter = np.array([-1, 1])

filter = np.array([-1, 1])

result = np.convolve(signal, filter, 'valid')

plt.stem(result)
plt.show()

import cv2
from matplotlib import pyplot as pyplot
import numpy as np

im = cv2.imread('/content/sample_data/black&white.jpg')

im.shape
(512, 512, 3)

im = cv2.cvtColor(im, cv2.COLOR_BGR2RGB)
im.shape

v_kernal = np.array([
    [-1, 0, 1],
    [-1, 0, 1],
    [-1, 0, 1]
])

h_kernal = np.array([
    [-1, -1, -1],
    [0, 0, 0],
    [1, 1, 1]
])

v_image = cv2.filter2D(im, -1, v_kernal)

plt.imshow(im, cmap='gray')
plt.title('Original Image')

plt.figure()
plt.imshow(v_image, cmap='gray')
plt.title('Vertical Edge Image')

plt.figure()
h_image = cv2.filter2D(im, -1, h_kernal)
plt.imshow(h_image, cmap='gray')
plt.title('Horizontal Edge Image')